name: CCDE_Cisco
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - numpy>=1.24.3
  - pandas>=2.0.3
  - spacy>=3.6.0
  - pillow>=10.0.0
  - tqdm>=4.65.0
  - pytest>=7.4.0
  - pip:
    - llama-index>=0.9.0
    - langchain>=0.0.267
    - pymupdf>=1.22.5
    - pdfplumber>=0.9.0
    - python-pptx>=0.6.21
    - python-docx>=0.8.11
    - markdown-it-py>=3.0.0
    - openpyxl>=3.1.2
    - tabula-py>=2.7.0
    - camelot-py>=0.11.0
    - pikepdf>=8.0.0
    - pdfminer.six>=20221105
    - pytesseract>=0.3.10
    - easyocr>=1.7.0
    - pdf2image>=1.16.3
    - sentence-transformers>=2.2.2
    - chromadb>=0.4.13
    - unstructured>=0.10.12
    - unstructured-inference>=0.6.3 